version: "3"

services:
  lakevision-be:
    image: localhost/lakevision-be
    container_name: lakevision-be
    build:
      context: ../be
      dockerfile: Dockerfile.be
    networks:
      iceberg_net:
    depends_on:
      - rest
      - minio
    volumes:
      - ./warehouse:/warehouse
      - ../be:/be
    environment:
      - PYICEBERG_CATALOG__DEFAULT__URI=http://rest:8181
      - PYICEBERG_CATALOG__DEFAULT__S3__ENDPOINT=http://minio:9000
      - PYICEBERG_CATALOG__DEFAULT__PY_IO_IMPL=pyiceberg.io.fsspec.FsspecFileIO
      - AWS_ENDPOINT=http://minio:9000
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
    ports:
      - 8000:8000
    links:
      - rest:rest
      - minio:minio
  lakevision-fe:
    image: localhost/lakevision-fe
    container_name: lakevision-fe
    build:
      context: ../fe
      dockerfile: Dockerfile.fe
    networks:
      iceberg_net:
    volumes:
      - ../fe/src:/fe/src
    environment:
      - PUBLIC_API_SERVER=http://localhost:8000
      - PUBLIC_API_SERVER_SERVER_SIDE=http://lakevision-be:8000
      - PORT=5173
    ports:
      - 5173:5173
    command: npm run dev -- --host
  rest:
    image: tabulario/iceberg-rest
    container_name: pyiceberg-rest
    networks:
      iceberg_net:
    ports:
      - 8181:8181
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
      - CATALOG_WAREHOUSE=s3://warehouse/
      - CATALOG_IO__IMPL=org.apache.iceberg.aws.s3.S3FileIO
      - CATALOG_S3_ENDPOINT=http://minio:9000
  minio:
    image: minio/minio
    container_name: pyiceberg-minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DOMAIN=minio
    networks:
      iceberg_net:
        aliases:
          - warehouse.minio
    ports:
      - 9001:9001
      - 9000:9000
    command: ["server", "/data", "--console-address", ":9001"]
  mc:
    depends_on:
      - minio
    image: minio/mc
    container_name: pyiceberg-mc
    networks:
      iceberg_net:
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add minio http://minio:9000 admin password) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc mb minio/warehouse;
      /usr/bin/mc policy set public minio/warehouse;
      tail -f /dev/null
      "
  loader:
    depends_on:
      - lakevision-be
      - minio
      - rest
    image: localhost/dataloader
    container_name: lakevision-dl
    build: .
    networks:
      iceberg_net:
    volumes:
      - ./warehouse:/warehouse
    environment:
      - PYICEBERG_CATALOG__DEFAULT__URI=http://rest:8181
      - PYICEBERG_CATALOG__DEFAULT__S3__ENDPOINT=http://minio:9000
      - PYICEBERG_CATALOG__DEFAULT__PY_IO_IMPL=pyiceberg.io.fsspec.FsspecFileIO
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
    entrypoint: >
      python /load_data.py

networks:
  iceberg_net:
