FROM node:21-alpine

WORKDIR /fe

COPY . .
RUN rm package-lock.json && rm -r node_modules
RUN npm install --package-lock-only
RUN npm ci
RUN npm install
#RUN npm run build
#RUN npm prune --production # Remove dev dependencies

EXPOSE 5173
ENV HOST=0.0.0.0

